Repository Team-bbangbbangs/EduKit-BE, pull requests merged in 2025-08, with the labels that each got.

#11 [EDMT-320] 유저 마이페이지 로직 구현
  edukit-api/build.gradle
  edukit-api/src/main/java/com/edukit/api/common/advice/GlobalExceptionHandler.java
  edukit-api/src/main/java/com/edukit/api/common/config/SwaggerConfig.java
  edukit-api/src/main/java/com/edukit/api/controller/auth/AuthController.java
  edukit-api/src/main/java/com/edukit/api/controller/member/MemberController.java
  edukit-api/src/main/java/com/edukit/api/controller/member/request/MemberProfileUpdateRequest.java
  edukit-api/src/main/java/com/edukit/api/controller/notice/AdminNoticeApi.java
  edukit-api/src/main/java/com/edukit/api/controller/notice/AdminNoticeController.java
  edukit-api/src/main/java/com/edukit/api/controller/notice/NoticeApi.java
  edukit-api/src/main/java/com/edukit/api/controller/notice/NoticeController.java
  edukit-api/src/main/java/com/edukit/api/security/config/SecurityConfig.java
  edukit-api/src/main/java/com/edukit/api/security/config/SecurityWhitelist.java
  edukit-core/src/main/java/com/edukit/core/auth/facade/AuthFacade.java
  edukit-core/src/main/java/com/edukit/core/member/entity/Member.java
  edukit-core/src/main/java/com/edukit/core/member/exception/MemberErrorCode.java
  edukit-core/src/main/java/com/edukit/core/member/facade/MemberFacade.java
  edukit-core/src/main/java/com/edukit/core/member/facade/response/MemberNicknameValidationResponse.java
  edukit-core/src/main/java/com/edukit/core/member/facade/response/MemberProfileGetResponse.java
  edukit-core/src/main/java/com/edukit/core/member/repository/MemberRepository.java
  edukit-core/src/main/java/com/edukit/core/member/repository/NicknameBannedWordRepository.java
  edukit-core/src/main/java/com/edukit/core/member/service/MemberService.java
Labels: ✨feat✨

#13 [EDMT-294] OpenAI 연동 과정에 Resilience4j 서킷 브레이커 적용
  edukit-api/src/main/java/com/edukit/api/controller/studentrecord/StudentRecordAIController.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/facade/StudentRecordAIFacade.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/facade/response/StudentRecordCreateResponse.java
  edukit-external/build.gradle
  edukit-external/src/main/java/com/edukit/external/ai/OpenAIService.java
  edukit-external/src/main/java/com/edukit/external/ai/response/OpenAIVersionResponse.java
  edukit-external/src/main/java/com/edukit/external/config/CircuitBreakerConfig.java
  edukit-external/src/test/java/com/edukit/external/ai/OpenAIServiceCircuitBreakerTest.java
  edukit-external/src/test/java/com/edukit/external/ai/OpenAIServiceIntegrationTest.java
Labels: ✨feat✨

#14 [EDMT-339] 교사 인증 배치 처리 로직 구현
  edukit-batch/build.gradle
  edukit-batch/src/main/java/com/edukit/batch/EdukitBatchApplication.java
  edukit-batch/src/main/java/com/edukit/batch/auth/handler/TeacherVerificationHandler.java
  edukit-batch/src/main/java/com/edukit/batch/auth/job/TeacherVerificationJob.java
  edukit-core/src/main/java/com/edukit/core/auth/repository/VerificationCodeRepository.java
  edukit-core/src/main/java/com/edukit/core/auth/service/VerificationCodeService.java
  edukit-core/src/main/java/com/edukit/core/auth/service/dto/MemberVerificationData.java
  edukit-core/src/main/java/com/edukit/core/common/config/JpaConfig.java
  edukit-core/src/main/java/com/edukit/core/common/handler/EmailEventListener.java
  edukit-core/src/main/java/com/edukit/core/member/entity/Member.java
  edukit-core/src/main/java/com/edukit/core/member/facade/MemberBatchFacade.java
  edukit-core/src/main/java/com/edukit/core/member/repository/MemberRepository.java
  edukit-core/src/main/java/com/edukit/core/member/service/MemberBatchService.java
  edukit-core/src/main/java/com/edukit/core/notice/facade/NoticeFacade.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/facade/StudentRecordAIFacade.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/EmailService.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/config/AwsSesConfig.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/AwsS3Properties.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/config/AwsS3Config.java
  edukit-external/src/main/java/com/edukit/external/config/AwsCredentialConfig.java
  edukit-external/src/main/java/com/edukit/external/config/AwsProperties.java
Labels: ✨feat✨

#17 [EDMT-338] 로그 파일 전송을 위한 Promtail 설정
  .github/workflows/batch-dev-cd.yml
  edukit-api/build.gradle
  edukit-api/src/main/resources/logback-spring.xml
  edukit-batch/build.gradle
  edukit-batch/src/main/resources/logback-spring.xml
  promtail-config.yml
Labels: ✨feat✨

#20 [EDMT-349] 교사 인증 자동화 시스템 구축
  .github/workflows/batch-dev-cd.yml
  build.gradle
  edukit-batch/build.gradle
  edukit-batch/src/main/java/com/edukit/batch/EdukitBatchApplication.java
  edukit-batch/src/main/java/com/edukit/batch/auth/handler/TeacherVerificationHandler.java
  edukit-batch/src/main/java/com/edukit/batch/auth/job/TeacherVerificationJob.java
  edukit-batch/src/main/java/com/edukit/batch/facade/MemberBatchFacade.java
  edukit-batch/src/main/java/com/edukit/batch/handler/TeacherVerificationLambdaHandler.java
  edukit-batch/src/main/java/com/edukit/batch/job/TeacherVerificationJob.java
  edukit-batch/src/main/resources/logback-spring.xml
  edukit-core/build.gradle
  edukit-external/build.gradle
  scripts/deploy-lambda.sh
Labels: ✨feat✨

#24 [EDMT-342] develop 브랜치 PR 시 dev 환경 빌드 워크플로우 추가
  .github/workflows/api-dev-ci.yml
  edukit-core/src/main/java/com/edukit/core/member/service/MemberBatchService.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/S3ServiceImpl.java
Labels: bug

#25 [EDMT-316] 엑셀로 학생 업로드 API 구현
  .github/workflows/api-dev-ci.yml
  edukit-api/src/main/java/com/edukit/common/filter/RequestLoggingFilter.java
  edukit-api/src/main/java/com/edukit/student/controller/StudentApi.java
  edukit-api/src/main/java/com/edukit/student/controller/StudentController.java
  edukit-api/src/main/java/com/edukit/student/facade/StudentFacade.java
  edukit-core/build.gradle
  edukit-core/src/main/java/com/edukit/core/student/db/entity/Student.java
  edukit-core/src/main/java/com/edukit/core/student/db/repository/StudentRepository.java
  edukit-core/src/main/java/com/edukit/core/student/exception/StudentErrorCode.java
  edukit-core/src/main/java/com/edukit/core/student/exception/StudentException.java
  edukit-core/src/main/java/com/edukit/core/student/service/ExcelService.java
  edukit-core/src/main/java/com/edukit/core/student/service/StudentService.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/StudentExcelRow.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/StudentKey.java
  edukit-core/src/main/java/com/edukit/core/student/utils/ExcelUtils.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/entity/StudentRecord.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/StudentRecordService.java
  edukit-external/src/main/java/com/edukit/external/ai/service/OpenAIServiceImpl.java
Labels: ✨feat✨

#30 [EDMT-382] Flyway 적용 및 이메일 인증 코드 시도 제한 로직 추가
  edukit-api/build.gradle
  edukit-api/src/main/java/com/edukit/auth/controller/v1/AuthV1Api.java
  edukit-api/src/main/resources/db/migration/V1__Initial_schema.sql
  edukit-api/src/main/resources/db/migration/V2__Add_attempts_locked_status_email_index.sql
  edukit-core/src/main/java/com/edukit/core/auth/db/entity/VerificationCode.java
  edukit-core/src/main/java/com/edukit/core/auth/db/enums/VerificationStatus.java
  edukit-core/src/main/java/com/edukit/core/auth/db/repository/VerificationCodeRepository.java
  edukit-core/src/main/java/com/edukit/core/auth/exception/AuthErrorCode.java
  edukit-core/src/main/java/com/edukit/core/auth/service/VerificationCodeService.java
Labels: ✨feat✨

#31 [EDMT-370] 엑셀 업로드 검증 로직 개선: 잘못된 행 수집 및 오류 응답 반환
  edukit-api/src/main/java/com/edukit/student/controller/StudentApi.java
  edukit-api/src/main/java/com/edukit/student/controller/StudentController.java
  edukit-api/src/main/java/com/edukit/student/facade/StudentFacade.java
  edukit-api/src/main/java/com/edukit/student/facade/response/StudentUploadResponse.java
  edukit-api/src/main/resources/db/migration/V1__Initial_schema.sql
  edukit-api/src/main/resources/db/migration/V3__Add_student_unique_constraint.sql
  edukit-core/src/main/java/com/edukit/core/student/db/entity/Student.java
  edukit-core/src/main/java/com/edukit/core/student/service/ExcelService.java
  edukit-core/src/main/java/com/edukit/core/student/service/StudentService.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/ExcelParseResult.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/InvalidStudentRow.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/StudentExcelRow.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/StudentKey.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/ValidStudentRow.java
Labels: ✨feat✨, ✏️refac✏️

#32 [EDMT-375] 생활기록부 관리 기능 추가
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordApi.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordController.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/request/StudentRecordUpdateRequest.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/response/StudentRecordsGetResponse.java
  edukit-api/src/main/resources/db/migration/V4__Add_student_name_normalized.sql
  edukit-core/src/main/java/com/edukit/core/common/converter/StudentRecordTypeConverter.java
  edukit-core/src/main/java/com/edukit/core/student/db/entity/Student.java
  edukit-core/src/main/java/com/edukit/core/student/exception/StudentErrorCode.java
  edukit-core/src/main/java/com/edukit/core/student/service/ExcelService.java
  edukit-core/src/main/java/com/edukit/core/student/service/StudentService.java
  edukit-core/src/main/java/com/edukit/core/student/utils/KoreanNormalizer.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/entity/StudentRecord.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/enums/StudentRecordType.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/repository/StudentRecordRepository.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/exception/StudentRecordErrorCode.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/StudentRecordService.java
Labels: ✨feat✨

#33 [EDMT-371] AWS SQS 연동
  edukit-api/src/main/java/com/edukit/auth/event/EmailSendEvent.java
  edukit-api/src/main/java/com/edukit/auth/event/MemberSignedUpEvent.java
  edukit-api/src/main/java/com/edukit/auth/event/PasswordFindEvent.java
  edukit-api/src/main/java/com/edukit/auth/facade/AuthFacade.java
  edukit-api/src/main/java/com/edukit/common/security/config/SecurityConfig.java
  edukit-api/src/main/java/com/edukit/member/event/MemberEmailUpdateEvent.java
  edukit-api/src/main/java/com/edukit/member/facade/MemberFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-api/src/main/java/com/edukit/studentrecord/event/AITaskCreateEvent.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordAIFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/response/StudentRecordTaskResponse.java
  edukit-api/src/main/resources/db/migration/V2__Add_attempts_locked_status.sql
  edukit-core/src/main/java/com/edukit/core/common/event/ai/AIEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/AIResponseGenerateEvent.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/DraftGenerationEvent.java
  edukit-core/src/main/java/com/edukit/core/common/event/mail/EmailEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/mail/PasswordChangeEmailEvent.java
  edukit-core/src/main/java/com/edukit/core/common/event/mail/TeacherVerificationEmailEvent.java
  edukit-core/src/main/java/com/edukit/core/common/service/SqsService.java
  edukit-core/src/main/java/com/edukit/core/common/service/response/OpenAIVersionResponse.java
  edukit-core/src/main/java/com/edukit/core/student/service/StudentService.java
  edukit-core/src/main/java/com/edukit/core/student/service/dto/ExcelParseResult.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/util/AIPromptGenerator.java
  edukit-external/build.gradle
  edukit-external/src/main/java/com/edukit/external/ai/config/CircuitBreakerConfig.java
  edukit-external/src/main/java/com/edukit/external/ai/service/OpenAIServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/AwsSesEmailMapper.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/EmailServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/config/AwsSesConfig.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/config/AwsSesProperties.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/S3ServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/config/AwsS3Config.java
  edukit-external/src/main/java/com/edukit/external/aws/s3/config/AwsS3Properties.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/SqsServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/config/AwsSqsConfig.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/config/AwsSqsProperties.java
  edukit-external/src/main/java/com/edukit/external/common/config/AsyncConfig.java
  edukit-external/src/test/java/com/edukit/external/ai/OpenAIServiceImplCircuitBreakerTest.java
  edukit-external/src/test/java/com/edukit/external/ai/OpenAIServiceImplIntegrationTest.java
Labels: ✨feat✨

#40 [EDMT-375] RedisTemplate 빈(Bean) 중복 정의로 인한 충돌 해결
  edukit-core/src/main/java/com/edukit/core/studentrecord/exception/StudentRecordErrorCode.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/StudentRecordService.java
  edukit-external/src/main/java/com/edukit/external/redis/RedisStreamServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/redis/config/RedisConfig.java
Labels: 🛠️ fix 🛠️

#42 [EDMT-408] 공지사항 이미지 관리 방식 변경
  edukit-api/src/main/java/com/edukit/admin/controller/AdminApi.java
  edukit-api/src/main/java/com/edukit/admin/controller/AdminController.java
  edukit-api/src/main/java/com/edukit/admin/controller/request/NoticeUpdateRequest.java
  edukit-api/src/main/java/com/edukit/notice/controller/NoticeApi.java
  edukit-api/src/main/java/com/edukit/notice/facade/NoticeFacade.java
  edukit-api/src/main/java/com/edukit/notice/facade/response/NoticeGetResponse.java
  edukit-core/src/main/java/com/edukit/core/notice/db/repository/NoticeFileRepository.java
  edukit-core/src/main/java/com/edukit/core/notice/service/NoticeService.java
Labels: ✏️refac✏️

#45 [EDMT-407] 요청 흐름 추적 체계 개선
  edukit-core/src/main/java/com/edukit/core/common/event/ai/AIEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/DraftGenerationEvent.java
  edukit-external/src/main/java/com/edukit/external/ai/service/OpenAIServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/SqsServiceImpl.java
Labels: ✨refac✨

#47 [EDMT-400] 비밀번호 찾기 시, 변경 링크 메일 전송 로직 구현
  docker-compose.dev.yml
  edukit-api/src/main/java/com/edukit/auth/controller/request/UpdatePasswordRequest.java
  edukit-api/src/main/java/com/edukit/auth/controller/v2/AuthV2Api.java
  edukit-api/src/main/java/com/edukit/auth/controller/v2/AuthV2Controller.java
  edukit-api/src/main/java/com/edukit/auth/facade/AuthFacade.java
  edukit-api/src/main/java/com/edukit/common/security/config/SecurityWhitelist.java
  edukit-common/src/main/java/com/edukit/common/infra/ServerInstanceManager.java
  edukit-core/src/main/java/com/edukit/core/auth/exception/AuthErrorCode.java
  edukit-core/src/main/java/com/edukit/core/auth/util/PasswordValidator.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/AIEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/mail/EmailEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/mail/EmailTemplate.java
  edukit-core/src/main/java/com/edukit/core/common/service/EmailService.java
  edukit-core/src/main/java/com/edukit/core/member/db/repository/MemberRepository.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/AwsSesEmailMapper.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/EmailServiceImpl.java
  edukit-external/src/main/java/com/edukit/external/aws/mail/config/AwsSesProperties.java
  edukit-external/src/main/java/com/edukit/external/common/config/AsyncConfig.java
  edukit-external/src/main/resources/templates/password-change.html
  promtail-config.yml
Labels: ✨feat✨

#52 [EDMT-374] 학생 도메인 인가 기능 추가
  edukit-api/src/main/java/com/edukit/common/security/config/SecurityConfig.java
  edukit-api/src/main/java/com/edukit/student/controller/StudentController.java
Labels: 🛠️ fix 🛠️
