Repository Team-bbangbbangs/EduKit-BE, pull requests merged in 2025-09, with the labels that each got.

#54 [EDMT-430] 학생 이름 목록 사이드바 로직 수정
  edukit-api/src/main/java/com/edukit/student/controller/StudentApi.java
  edukit-api/src/main/java/com/edukit/student/facade/StudentFacade.java
  edukit-api/src/main/java/com/edukit/student/facade/response/StudentNamesGetResponse.java
Labels: ✨feat✨

#55 [EDMT-404] SQS 메세지 전송 시 멱등키 추가
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/exception/StudentRecordErrorCode.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/SqsServiceImpl.java
Labels: ✨feat✨

#56 [EDMT-406] 단계별 진행상황 전송
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIApi.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordAIFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/response/StudentRecordTaskResponse.java
  edukit-api/src/main/resources/db/migration/V8__Remove_student_record_ai_task_columns.sql
  edukit-core/src/main/java/com/edukit/core/common/event/ai/AIEventListener.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/AIProgressMessage.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/AIResponseMessage.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/DraftGenerationEvent.java
  edukit-core/src/main/java/com/edukit/core/common/event/ai/dto/SSEMessage.java
  edukit-core/src/main/java/com/edukit/core/common/service/SqsService.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/entity/StudentRecordAITask.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/db/enums/AITaskStatus.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/exception/StudentRecordErrorCode.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/AITaskService.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/SSEChannelManager.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/enums/AITaskStatus.java
  edukit-external/src/main/java/com/edukit/external/aws/sqs/SqsServiceImpl.java
Labels: ✨feat✨

#58 [EDMT-437] 운영 환경 스크립트 설정
  .github/workflows/api-prod-cd.yml
  Dockerfile-prod
  docker-compose.prod.yml
  edukit-api/src/main/resources/db/migration/V9__Drop_post_tables.sql
  edukit-core/src/main/java/com/edukit/core/post/db/entity/Post.java
  edukit-core/src/main/java/com/edukit/core/post/db/entity/PostComment.java
  edukit-core/src/main/java/com/edukit/core/post/db/entity/PostFile.java
  edukit-core/src/main/java/com/edukit/core/post/db/entity/PostLike.java
  edukit-core/src/main/java/com/edukit/core/post/db/enums/PostCategory.java
  edukit-core/src/main/java/com/edukit/core/post/db/enums/PostFileCategory.java
  edukit-core/src/main/java/com/edukit/core/post/exception/PostException.java
Labels: ✨feat✨

#64 Release v2.1.1
  edukit-api/src/main/java/com/edukit/common/security/filter/ExceptionHandlerFilter.java
  edukit-api/src/main/java/com/edukit/common/security/handler/JwtAccessDeniedHandler.java
  edukit-api/src/main/java/com/edukit/common/security/handler/JwtAuthenticationEntryPoint.java
  edukit-api/src/main/java/com/edukit/common/security/utils/AllowedOriginValidator.java
Labels: 📌release📌

#65 [EDMT-407] Loki 라벨 구조 개선: 로그 필터링을 위한 label 추가
  promtail-config.yml
Labels: ✨refac✨

#66 [EDMT-452] 커스텀 메트릭 추가
  build.gradle
  edukit-api/build.gradle
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordAIFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordFacade.java
  edukit-common/src/main/java/com/edukit/common/annotation/AIGenerationMetrics.java
  edukit-common/src/main/java/com/edukit/common/annotation/StudentRecordMetrics.java
  edukit-core/build.gradle
  edukit-core/src/main/java/com/edukit/core/studentrecord/aop/StudentRecordMetricsAspect.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/GenerationTrackingService.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/StudentRecordMetricsService.java
Labels: ✨feat✨

#69 [EDMT-451] Claude Code 개발 도구 및 자동화 스크립트 추가
  .claude/agents/flyway-migration-generator.md
  .claude/agents/swagger-documenter.md
  .claude/agents/test-generator.md
  .claude/commands/commit.md
  .claude/commands/pr.md
Labels: ✨feat✨

#70 Release v2.1.2
  .claude/agents/flyway-migration-generator.md
  .claude/agents/swagger-documenter.md
  .claude/agents/test-generator.md
  .claude/commands/commit.md
  .claude/commands/pr.md
  .github/workflows/api-dev-cd.yml
  .github/workflows/api-prod-cd.yml
  build.gradle
  edukit-api/build.gradle
  edukit-api/src/main/java/com/edukit/EdukitApiApplication.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordAIFacade.java
  edukit-api/src/main/java/com/edukit/studentrecord/facade/StudentRecordFacade.java
  edukit-common/src/main/java/com/edukit/common/annotation/AIGenerationMetrics.java
  edukit-common/src/main/java/com/edukit/common/annotation/StudentRecordMetrics.java
  edukit-core/build.gradle
  edukit-core/src/main/java/com/edukit/core/studentrecord/aop/StudentRecordMetricsAspect.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/RecordGenerationTracker.java
  edukit-core/src/main/java/com/edukit/core/studentrecord/service/StudentRecordMetricsCounter.java
  promtail-config.yml
Labels: 📌release📌

#74 [EDMT-454] Docker 엔트리포인트 JAVA_OPTS 설정 개선
  Dockerfile-dev
  Dockerfile-prod
  docker-compose.dev.yml
  docker-compose.prod.yml
  jmx-config.yml
Labels: ✨refac✨

#75 [EDMT-450] 패키지 구조 개선
  .claude/CLAUDE.md
  .gitignore
  docker-compose.prod.yml
  edukit-api/src/main/java/com/edukit/auth/security/config/SecurityWhitelist.java
  edukit-api/src/main/java/com/edukit/studentrecord/controller/StudentRecordAIController.java
  edukit-core/src/main/java/com/edukit/core/common/converter/StudentRecordTypeConverter.java
Labels: ✨refac✨
